### ISSUE TITLE
Prepare Pitch for FAC5 Summer of Code in Portugal?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/alc#2]
@iteles as discussed on our evening walk. :walking: 
How much detail/info do we need to put together for a "pitch" to FAC5?

**Comment by nelsonic** [comment]
@tonydaly would you consider coming out to Portugal for a Weekend/Week to get some sun, ride some [_offroad segways_](http://www.tripadvisor.co.uk/Attraction_Review-g189154-d1491975-Reviews-Silencetour_Segway_Nature_Guided_Tours-Cascais_Lisbon_District_Central_Portugal.html) and write a bit of code for this #OpenSource project...? :wink:

**Comment by tonydaly** [comment]
@nelsonic could totally do a weekend in August?!

**Comment by nelsonic** [comment]
@tonydaly if you are still up for visiting for a weekend in August, please checkout https://github.com/dwyl/summer-2015 for dates. let us know! we would :heart: to have you over!

**Comment by iteles** [comment]
So this happened, and **22 people** [joined us in Portugal over the summer](https://twitter.com/search?q=%23dwylsummer). There were 2 more people who signed up that we couldn't accommodate in August due to lack of space and sadly couldn't join us in for July and there were also 2 additional people who signed up who had to drop out at the last minute.

I'd say 26 people wanting to come is a pretty successful pitch :grin:
